<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-19T11:51:06 IST" name="Default suite" finished-at="2025-05-19T11:51:59 IST" duration-ms="53470">
    <groups>
    </groups>
    <test started-at="2025-05-19T11:51:06 IST" name="Default test" finished-at="2025-05-19T11:51:59 IST" duration-ms="53470">
      <class name="TestClass.Lr_ChangePassTest">
        <test-method is-config="true" signature="initializeBrowser()[pri:0, instance:TestClass.Lr_ChangePassTest@45385f75]" started-at="2025-05-19T11:51:06 IST" name="initializeBrowser" finished-at="2025-05-19T11:51:07 IST" duration-ms="1570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBrowser -->
        <test-method signature="LR_Changepassword()[pri:0, instance:TestClass.Lr_ChangePassTest@45385f75]" started-at="2025-05-19T11:51:07 IST" name="LR_Changepassword" finished-at="2025-05-19T11:51:59 IST" duration-ms="51355" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Failed: Server error on LR changepassword profile page.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Failed: Server error on LR changepassword profile page.
at org.testng.Assert.fail(Assert.java:111)
at TestClass.Lr_ChangePassTest.LR_Changepassword(Lr_ChangePassTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LR_Changepassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestClass.Lr_ChangePassTest@45385f75]" started-at="2025-05-19T11:51:59 IST" name="tearDown" finished-at="2025-05-19T11:51:59 IST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestClass.Lr_ChangePassTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
